# Generated by Django 4.1 on 2023-11-14 13:05

import app.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdeaform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('College_Name', models.CharField(max_length=50)),
                ('Branch_Name', models.CharField(max_length=50)),
                ('Idea_Description', models.CharField(max_length=500)),
                ('Upload_url', models.URLField()),
                ('Approved', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('Date', models.DateField()),
                ('file', app.app.ContentTypeRestrictedFileField(upload_to='pdf')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
