# Generated by Django 4.1.2 on 2023-11-16 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='EventName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='target_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
