# Generated by Django 4.1.2 on 2023-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_countdown_eventname_alter_countdown_target_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('target_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Countdown',
        ),
    ]
