# Generated by Django 4.1.2 on 2023-11-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentideaform_date'),
        ('app', '0005_eventtimer_delete_countdown'),
    ]

    operations = [
    ]
