# Generated by Django 4.1.2 on 2023-11-17 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_merge_20231117_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentideaform',
            name='Reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='studentideaform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Approved',
            field=models.IntegerField(choices=[('Proccing', 'Proccing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Proccing'),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 20, 58, 919892)),
        ),
    ]
