# Generated by Django 4.1.2 on 2023-11-17 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentideaform_reason_studentideaform_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentideaform',
            name='Approved',
            field=models.CharField(choices=[('Proccing', 'Proccing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Proccing', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 32, 48, 201002)),
        ),
    ]
