# Generated by Django 4.1.2 on 2023-11-17 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_studentideaform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='companeyName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 17, 32, 45, 963185)),
        ),
    ]
