# Generated by Django 4.1.2 on 2023-11-20 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_panelist_companeyname_alter_studentideaform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimer',
            name='Upload_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='eventtimer',
            name='image',
            field=models.ImageField(default='', upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 11, 12, 10, 624761)),
        ),
    ]
