# Generated by Django 4.2.7 on 2023-11-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_collaboration_contact_alter_studentideaform_date'),
        ('app', '0016_eventtimer_eventdescription_and_more'),
    ]

    operations = [
    ]
