# Generated by Django 4.1.2 on 2023-11-21 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20231120_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 8, 50, 18, 972752)),
        ),
    ]
