# Generated by Django 4.1.2 on 2023-11-21 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_collaboration_alter_studentideaform_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Brand_Agency', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=100)),
                ('Collaboration_Type', models.CharField(max_length=25)),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 11, 21, 9, 31, 16, 310183))),
            ],
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 9, 31, 16, 310183)),
        ),
    ]
