# Generated by Django 4.1.2 on 2023-11-24 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_collaboration_alter_studentideaform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimer',
            name='Approved',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 4, 58, 530881)),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 4, 58, 530881)),
        ),
    ]
