# Generated by Django 4.1.2 on 2023-11-24 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_eventtimer_approved_alter_collaboration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtimer',
            name='Approved',
        ),
        migrations.AddField(
            model_name='event',
            name='Approved',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='sluge',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 17, 29, 52843)),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 17, 29, 46843)),
        ),
    ]
