# Generated by Django 4.1.2 on 2023-11-24 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_eventtimer_approved_event_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Approved',
            new_name='activeEvent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sluge',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 18, 35, 860199)),
        ),
        migrations.AlterField(
            model_name='studentideaform',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 18, 35, 842389)),
        ),
    ]
